worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        
        # Cache settings
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
            access_log off;
        }

        # Serve microfrontend apps
        location /forms-flow-admin {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-components {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-integration {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-nav {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-rsbcservice {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-service {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location /forms-flow-theme {
            root /usr/share/nginx/html;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        # Serve gzipped JavaScript files correctly
        location ~* \.gz\.js$ {
            root /usr/share/nginx/html;
            gzip off;
            add_header Content-Encoding gzip;
            add_header Content-Type application/javascript;
            access_log off;
        }
    }
}
