worker_processes auto;
error_log /var/log/nginx/error.log;

pid /tmp/nginx.pid;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
    default_type application/octet-stream;
    server_tokens off;
    underscores_in_headers on;

    # Logging Format
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        gzip on;
        gzip_types text/css application/json application/javascript text/xml application/xml application/xml+rss;

        # Security Headers
        add_header Content-Security-Policy "default-src * data: blob: filesystem: 'unsafe-inline' 'unsafe-eval'";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options "SAMEORIGIN";      

        # CORS
        location / {
            add_header 'Access-Control-Allow-Origin' '*';
            try_files $uri $uri/ /index.html;
        }
        
        # Cache settings
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # Serve microfrontend apps
        location /forms-flow-admin { try_files $uri $uri/ /index.html; }
        location /forms-flow-components { try_files $uri $uri/ /index.html; }
        location /forms-flow-integration { try_files $uri $uri/ /index.html; }
        location /forms-flow-nav { try_files $uri $uri/ /index.html; }
        location /forms-flow-rsbcservice { try_files $uri $uri/ /index.html; }
        location /forms-flow-service { try_files $uri $uri/ /index.html; }
        location /forms-flow-theme { try_files $uri $uri/ /index.html; }

        # Serve gzipped JavaScript files
        location ~* \.gz\.js$ {
            gzip off;
            add_header Content-Encoding gzip;
            add_header Content-Type application/javascript;
            default_type application/javascript;
        }

        # Default error page
        error_page 500 502 503 504 /50x.html;
        location = /50x.html { }
    }
}
